### ISSUE TITLE
Bug Report: Cannot update error

### ISSUE THREAD

**Issue by dch82** [vlinkz/nix-software-center#40]
Whenever I try to update anything on this app, it produces an error message:

```
error: the following required arguments were not provided:
  --output <OUTPUT>

Usage: nsc-helper channel --output <OUTPUT> --rebuild --generations <GENERATIONS> <ARGUMENTS>...

For more information, try '--help'.
```
Thank you!

**Comment by dch82** [comment]
After a fresh reinstall of NixOS (don't ask) all seems to be normal now.

**Comment by vlinkz** [comment]
Hm weird. I did make some changes regarding that menu yesterday though to address sometime where it wouldn't show up properly, so probably inadvertently fixed this too :)
