### ISSUE TITLE
"Open interactive shell" fails silently

### ISSUE THREAD

**Issue by tejing1** [vlinkz/nix-software-center#5]
When I try to "Open interactive shell" for `wezterm` (just what I happened to try), nothing happens at all, on console or elsewhere. No processes are started, or at least none that last long enough to see.

**Comment by vlinkz** [comment]
Should probably work on the latest commit since now `gnome-console` is included in the path

**Comment by tejing1** [comment]
Sorry it took me so long to get back to this. Yes, it works now. (though gnome-console isn't exactly my favorite terminal emulator, but that's a feature for later)
